import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AYBU Moodle System",
  description: "Generated by AYBU Moodle",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Main Header */}
        <header className="bg-white shadow-sm">
          
          <div className="max-w-7x2 mx-auto px-6 py-4 flex items-start justify-between">
            <img src="/ogmer.png" alt="Logo" width={200} height={50} />
            {/* Left Side - University Info */}
            <div className="flex space-x-8">
              <div className="flex flex-col">
                <h1 className="text-lg font-bold text-gray-800 mb-1">Biz Kimiz?</h1>
                <p className="text-xs text-gray-600 leading-tight">
                  Ankara Yıldırım Beyazıt Üniversitesi<br />
                  ÖĞMER<br />
                  Öğrenme ve Öğretme Merkezi
                </p>
              </div>

              {/* Address Section with Icon */}
              <div className="flex items-start space-x-2">
                <div className="mt-1">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                </div>
                <div>
                  <p className="text-xs font-medium text-gray-800">Adres</p>
                  <p className="text-xs text-gray-600 leading-tight">
                    Milli İrade Binası<br />
                    A Blok 5. Kat <br />
                    06010 Etlik<br />
                    Keçiören/ANKARA
                  </p>
                </div>
              </div>

              {/* Contact Section with Icon */}
              <div className="flex items-start space-x-2">
                <div className="mt-1">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                  </svg>
                </div>
                <div>
                  <p className="text-xs font-medium text-gray-800">Telefon</p>
                  <p className="text-xs text-gray-600">0312 999 99 99</p>{/* Numara Düzenlenecek*/}
                </div>
              </div>

              {/* Email Section with Icon */}
              <div className="flex items-start space-x-2">
                <div className="mt-1">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                  </svg>
                </div>
                <div>
                  <p className="text-xs font-medium text-gray-800">E-posta</p>
                  <p className="text-xs text-gray-600">ÖĞMER@.tr</p>{/* Email Düzenlenecek*/}
                </div>
              </div>
              {/* Notification Dropdown */}
              <div className="relative group">
                <button className="relative p-1 text-gray-600 hover:text-gray-900">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                  </svg>
                 
                </button>
                
                <div className="absolute right-0 mt-2 w-80 bg-white rounded-md shadow-lg py-1 z-50 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300 transform translate-y-1">
                  <div className="px-4 py-2 border-b border-gray-200">
                    <h3 className="text-lg font-semibold">Bildirimler</h3>
                  </div>
                </div>
              </div>
            </div>

            {/* Right Side - Navigation */}
            <nav className="flex items-center space-x-6 mt-1">
              {/* Birim Temsilcileri Link */}
              <Link 
                href="/representatives" 
                className="text-gray-700 hover:text-blue-800 transition font-medium text-sm"
              >
                Birim Temsilcileri
              </Link>

              {/* AYBUZEM YOUTUBE Dropdown */}
              <div className="relative group">
                <button className="flex items-center space-x-1 text-gray-700 hover:text-blue-800 transition font-medium text-sm">
                  <span>ÖĞMER YOUTUBE</span>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                <div className="absolute left-0 mt-2 w-56 bg-white rounded-md shadow-lg py-1 z-10 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300">
                  <Link href="/youtube/channel" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Kanalımıza Abone Olun</Link>
                  <Link href="/youtube/tutorials" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Eğitim Videoları</Link>
                </div>
              </div>

              {/* Kurslarım Dropdown */}
              <div className="relative group">
                <button className="flex items-center space-x-1 text-gray-700 hover:text-blue-800 transition font-medium text-sm">
                  <span>Kurslarım (6)</span>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                <div className="absolute right-0 mt-2 w-64 bg-white rounded-md shadow-lg py-1 z-10 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300">
                  <div className="px-4 py-2 border-b border-gray-100">
                    <p className="text-sm font-medium text-gray-800">Aktif Kurslarım</p>
                  </div>
                  <Link href="/course/1" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Bilgisayar Programlama I</Link>
                  <Link href="/course/2" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Veri Yapıları</Link>
                  <Link href="/course/3" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Algoritma Analizi</Link>
                  <Link href="/course/4" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Yapay Zeka</Link>
                  <Link href="/course/5" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Veritabanı Sistemleri</Link>
                  <Link href="/course/6" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Web Programlama</Link>
                </div>
              </div>
              {/* Profile Dropdown */}
              <div className="relative">
                <div className="group inline-block">
                  <button className="flex items-center space-x-1 text-gray-700 hover:text-red-600 transition">
                    <span>My Profile</span>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </button>
                  
                  {/* Dropdown Menu */}
                  <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-10 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300">
                    <div className="px-4 py-2 border-b border-gray-100">
                      <p className="text-sm font-medium text-gray-800">öğrenci numarası</p>{/* bu alan dinamik yapılacak */}
                    </div>
                    <Link href="/profile" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Profil</Link>
                    <Link href="/grades" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Başarı notları</Link>
                    <Link href="/calendar" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Takvim</Link>
                    <Link href="/files" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Kişisel dosyalar</Link>
                    <Link href="/reports" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Raporlar</Link>
                    <Link href="/preferences" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Tercihler</Link>
                    <div className="border-t border-gray-100"></div>
                    <Link href="/" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Çıkış yap</Link>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="bg-white min-h-screen">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-900 text-white text-sm p-4 text-center">
          <p>AYBU Moodle System &copy; 2025 | <Link href="#" className="text-red-400">Creative Commons</Link></p>
          <div className="flex justify-center space-x-3 mt-2">
            <Link href="#"><Image src="/youtube.svg" alt="YouTube" width={24} height={24} /></Link>
            <Link href="#"><Image src="/twitter.svg" alt="Twitter" width={24} height={24} /></Link>
            <Link href="#"><Image src="/facebook.svg" alt="Facebook" width={24} height={24} /></Link>
          </div>
        </footer>
      </body>
    </html>
  );
}